// <auto-generated />
using System;
using BrewTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrewTrack.Migrations
{
    [DbContext(typeof(BrewTrackDbContext))]
    partial class BrewTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BrewTrack.Models.ApiSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ApiSourceId");

                    b.Property<string>("ApiSourceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("api_sources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf63956f-f675-4121-a6f8-26dfb40bd750"),
                            ApiSourceName = "Weather",
                            DateCreated = new DateTime(2023, 6, 7, 14, 5, 41, 60, DateTimeKind.Utc).AddTicks(8118)
                        },
                        new
                        {
                            Id = new Guid("340e1ee2-3171-4f09-b06f-408e6fa149ca"),
                            ApiSourceName = "Breweries",
                            DateCreated = new DateTime(2023, 6, 7, 14, 5, 41, 60, DateTimeKind.Utc).AddTicks(8127)
                        });
                });

            modelBuilder.Entity("BrewTrack.Models.BrewPub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("brewPubId");

                    b.Property<string>("Brewery_Type")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Website_Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("brewpubs");
                });

            modelBuilder.Entity("BrewTrack.Models.CachedTimeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("CachedTimeLineId");

                    b.Property<Guid>("ApiSourceRefId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApiSourceRefId");

                    b.HasIndex("Date")
                        .IsDescending();

                    b.ToTable("cached_timeline");
                });

            modelBuilder.Entity("BrewTrack.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("BrewTrack.Models.UserHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserHistoryId");

                    b.Property<int>("LastPage")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("user_history");
                });

            modelBuilder.Entity("BrewTrack.Models.WeatherForeCastDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("WeatherForeCastDetailsId");

                    b.Property<int>("AirTemprature")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("WeatherForCastHeaderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WeatherForeCastHeaderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WeatherForeCastHeaderId");

                    b.ToTable("weather_forecast_details");
                });

            modelBuilder.Entity("BrewTrack.Models.WeatherForeCastHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("WeatherForecastHeaderId");

                    b.Property<Guid>("CachedTimeLineId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("weather_forcast_header");
                });

            modelBuilder.Entity("BrewTrack.Models.CachedTimeline", b =>
                {
                    b.HasOne("BrewTrack.Models.ApiSource", null)
                        .WithMany("Timeline")
                        .HasForeignKey("ApiSourceRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrewTrack.Models.WeatherForeCastDetails", b =>
                {
                    b.HasOne("BrewTrack.Models.WeatherForeCastHeader", null)
                        .WithMany("WeatherForeCastDetails")
                        .HasForeignKey("WeatherForeCastHeaderId");
                });

            modelBuilder.Entity("BrewTrack.Models.ApiSource", b =>
                {
                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("BrewTrack.Models.WeatherForeCastHeader", b =>
                {
                    b.Navigation("WeatherForeCastDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
